CREATE TABLE IF NOT EXISTS managers ( 
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  login VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS checklist (
  id SERIAL PRIMARY KEY,
  title VARCHAR(80) NOT NULL,
  description VARCHAR(250) NOT NULL,
  sector VARCHAR(50) NOT NULL

);

